export const PRODUCT_CATEGORIES = {
  alimentacao: [
    'Frutas e Verduras',
    'Legumes',
    'Grãos e Cereais',
    'Queijos e Frios',
    'Carnes e Peixes',
    'Pães e Bolos Artesanais',
    'Lanches Prontos',
    'Bebidas Naturais (sucos, vitaminas, cafés)',
    'Doces e Sobremesas',
    'Comidas Típicas',
    'Temperos e Condimentos',
    'Produtos Veganos / Naturais',
  ],
  roupas: [
    'Moda Feminina',
    'Moda Masculina',
    'Moda Infantil',
    'Roupas Fitness',
    'Moda Praia',
    'Moda Plus Size',
    'Acessórios (bolsas, carteiras)',
    'Bijuterias e Semijoias',
    'Calçados',
  ],
  artesanato: [
    'Produtos em Madeira',
    'Produtos em Crochê / Tricô',
    'Artesanato em Tecido',
    'Pinturas e Quadros',
    'Velas Aromáticas',
    'Sabonetes Artesanais',
    'Decoração',
    'Esculturas e Peças Manuais',
  ],
  beleza: [
    'Cosméticos Naturais',
    'Produtos de Higiene',
    'Óleos Essenciais',
    'Perfumes Artesanais',
    'Itens de Massagem e Spa',
  ],
  servicos: [
    'Chaveiro',
    'Conserto de Roupas',
    'Manutenção de Eletrônicos',
    'Serviços de Estética',
    'Barbearia / Cabelo',
    'Assistência Geral',
  ],
  outros: [
    'Pets (acessórios, petiscos)',
    'Produtos Sustentáveis',
    'Jardinagem / Flores',
    'Utensílios Domésticos',
    'Importados',
  ],
} as const;

export const CATEGORY_LABELS = {
  alimentacao: 'Alimentação',
  roupas: 'Roupas e Acessórios',
  artesanato: 'Artesanato',
  beleza: 'Beleza e Bem-estar',
  servicos: 'Serviços',
  outros: 'Outros',
} as const;
